version: '3.8'

services:
  puppeteer-service:
    image: my-puppeteer-service
    container_name: puppeteer_service
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - .:/app  # Mount the local directory for live updates
      - /app/node_modules  # Prevent overwriting node_modules
    command: npm run dev  # Use nodemon for watching files
